# 1. Matches the name of the 'customer-service.yml' file in the remote repo
spring.application.name=order-service

# 2. Instructs the app to query this URI first before executing internal initializations
spring.config.import=optional:configserver:http://localhost:8888